### ISSUE TITLE
Failed to run the processing module "VirusTotal"

### ISSUE THREAD

**Issue by sfoxdev** [CheckPointSW/Cuckoo-AWS#11]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### The log, error, files etc can be found at: 
```
Failed to run the processing module "VirusTotal" for task #6:
Traceback (most recent call last):
  File "/opt/cuckoo/cuckoo/core/plugins.py", line 241, in process
    data = current.run()
  File "/opt/cuckoo/cuckoo/processing/virustotal.py", line 61, in run
    row["virustotal"] = self.scan_file(row["path"], summary=True)
  File "/opt/cuckoo/cuckoo/processing/virustotal.py", line 78, in scan_file
    return self.vt.file_scan(filepath)
  File "/opt/cuckoo/cuckoo/common/virustotal.py", line 174, in file_scan
    r = self._request_json(self.FILE_SCAN, data=data, files=files)
  File "/opt/cuckoo/cuckoo/common/virustotal.py", line 76, in _request_json
    r = requests.post(url, timeout=self.timeout, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 858, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 311, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 301, in _send_until_done
    return self.connection.send(data)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1256, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1166, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (32, 'EPIPE')
```

I just installed Cuckoo-AWS on new instance Ubuntu 18.04 and getting such error after file analysis at top in Summary.

**Comment by chkp-orank** [comment]
Hi @sfoxdev,

I'm starting to investigate your issue, not sure if it is something related to AWS machinery.

According to your attached log, this is your sixth task. Were the first five tasks completed successfully?

**Comment by chkp-orank** [comment]
ok,

I understand that you enabled the virustotal option at processing.conf.
It seems that you have a connectivity issue to VT.

Make sure that the Nest has the port 443 opened at the outbound side.

Also, your exception occurred while it was posting a file to be scanned at VT.
I recommend you to run that same scan manually from your Cuckoo's Nest.
Here is how to do that according to VT.
https://developers.virustotal.com/reference#file-scan

**Comment by chkp-mostafaw** [comment]
@sfoxdev, please check your connection to virus-total as @chkp-orank advised you.

For now, we are closing this issue, if the error reoccurs then please open a new issue.
