### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_installed_distributions' running cuckoo

### ISSUE THREAD

**Issue by KingUdo** [CheckPointSW/Cuckoo-AWS#14]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is:
When starting cuckoo I get the following error:
```
(venv) root@ip-192-168-1-10:/opt/cuckoo/Cuckoo-AWS# cuckoo

                      __
  .----..--.--..----.|  |--..-----..-----.
  |  __||  |  ||  __||    < |  _  ||  _  |
  |____||_____||____||__|__||_____||_____|

 Cuckoo Sandbox 2.0.6
 www.cuckoosandbox.org
 Copyright (c) 2010-2018

 Checking for updates...
 Outdated! Cuckoo Sandbox version 2.0.7 is available now.

 Our latest blogposts:
 * Cuckoo Sandbox 2.0.7, June 19, 2019.
   Stability and security
   More at https://cuckoosandbox.org/blog/207-interim-release

 * IQY malspam campaign, October 15, 2018.
   Analysis of a malspam campaign leveraging .IQY (Excel Web Query) files containing DDE to achieve code execution.
   More at https://hatching.io/blog/iqy-malspam

 * Hooking VBScript execution in Cuckoo, October 03, 2018.
   Details on implementation of Visual Basic Script instrumentation for Cuckoo Monitor for extraction of dynamically executed VBScript.
   More at https://hatching.io/blog/vbscript-hooking

 * Cuckoo Sandbox 2.0.6 pentest, September 18, 2018.
   Cuckoo Sandbox 2.0.6 public pentest performed by Cure53 and sponsored by PolySwarm!
   More at https://hatching.io/blog/cuckoo-206-pentest

 * Cuckoo Sandbox 2.0.6, June 07, 2018.
   Interim release awaiting the big release.
   More at https://cuckoosandbox.org/blog/206-interim-release

2019-10-02 15:12:18,854 [cuckoo] WARNING: It appears that you haven't loaded any Cuckoo Signatures. Signatures are highly recommended and improve & enrich the information extracted during an analysis. They also make up for the analysis score that you see in the Web Interface - so, pretty important!
2019-10-02 15:12:18,854 [cuckoo] WARNING: You'll be able to fetch all the latest Cuckoo Signaturs, Yara rules, and more goodies by running the following command:
2019-10-02 15:12:18,854 [cuckoo] INFO: $ cuckoo community
2019-10-02 15:12:18,856 [cuckoo.core.scheduler] INFO: Using "aws" as machine manager
2019-10-02 15:12:18,955 [cuckoo.machinery.aws] INFO: connecting to AWS:None
Traceback (most recent call last):
  File "/opt/cuckoo/Cuckoo-AWS/venv/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo', 'console_scripts', 'cuckoo')()
  File "/opt/cuckoo/Cuckoo-AWS/venv/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/cuckoo/Cuckoo-AWS/venv/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/cuckoo/Cuckoo-AWS/venv/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/opt/cuckoo/Cuckoo-AWS/venv/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/cuckoo/Cuckoo-AWS/venv/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/cuckoo/Cuckoo-AWS/venv/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/cuckoo/Cuckoo-AWS/cuckoo/main.py", line 242, in main
    sys.stderr.write(exception_message())
  File "/opt/cuckoo/Cuckoo-AWS/cuckoo/common/utils.py", line 262, in exception_message
    for package in pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'
```

##### My Cuckoo version and operating system are:
I just pulled a fresh version from Github 
I'm running a Ubuntu 18.04.3 LTS on a t2.medium in aws

##### This can be reproduced by:
following the installation instructions

**Comment by KingUdo** [comment]
Found the error myself.... you need to downgrade pip:
`pip install pip==9.0.3`
