### ISSUE TITLE
Cuckoo with webserver does not attempt to connect to guest

### ISSUE THREAD

**Issue by ashesbelow** [CheckPointSW/Cuckoo-AWS#17]
I am running the cuckoo web server. I can access the page, but when I attempt to upload an exe, the command line on the Nest server shows the following error:

2019-12-03 20:41:55,131 [django.request] ERROR: Internal Server Error: /submit/api/presubmit
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/home/ec2-user/Cuckoo-AWS/cuckoo/web/controllers/submission/api.py", line 54, in presubmit
    files = request.FILES.getlist("files[]")
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 150, in _get_files
    self._load_post_and_files()
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 260, in _load_post_and_files
    self._post, self._files = self.parse_file_upload(self.META, data)
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 225, in parse_file_upload
    return parser.parse()
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 149, in parse
    for item_type, meta_data, field_stream in Parser(stream, self._boundary):
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 626, in __iter__
    for sub_stream in boundarystream:
  File "/usr/lib64/python2.7/site-packages/django/utils/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 439, in __next__
    return LazyStream(BoundaryIter(self._stream, self._boundary))
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 466, in __init__
    unused_char = self._stream.read(1)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 337, in read
    out = b''.join(parts())
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 330, in parts
    chunk = next(self)
  File "/usr/lib64/python2.7/site-packages/django/utils/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 352, in __next__
    output = next(self._producer)
  File "/usr/lib64/python2.7/site-packages/django/utils/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 414, in __next__
    data = self.flo.read(self.chunk_size)
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 294, in read
    six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 292, in read
    return self._stream.read(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 57, in read
    result = self.buffer + self._read_limited(size - len(self.buffer))
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 45, in _read_limited
    result = self.stream.read(size)
  File "/usr/lib64/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
UnreadablePostError: [Errno 104] Connection reset by peer
[03/Dec/2019 20:41:55] "POST /submit/api/presubmit HTTP/1.1" 500 12976
- Broken pipe from ('XX.XXX.XX.83', 36893)

Also, when attempting to enter a URL for analysis, the web site seems to redirect to the correct pages (pending, etc) but does nothing. Just remains in "pending" status perpetually. No errors are shown on the Nest server. I also started TCPDump on the Nest Server while going through the URL submission process and the Nest server doesnt even seem to attempt to connect to the guest machine. The only IPs that show are AWS infrastructure addresses.

Help?

**Comment by chkp-mostafaw** [comment]
Are you sure you have connectivity between results server and nest? Maybe security group is preventing traffic to flow between them?

**Comment by harshn1904** [comment]
Hi guys!
how did you setup cuckoo on aws? can you please guide me?
thank you!!
