### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ELyndin** [CheckPointSW/Cuckoo-AWS#25]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

##### My issue is: 
installation error

##### My Cuckoo version and operating system are: 
2.0.7, Ubuntu 20.04.1 LTS

##### This can be reproduced by:
According "Installation instructions" and "Docs » Installation » Preparing the Host » Requirements" we did:
git clone https://github.com/CheckPointSW/Cuckoo-AWS

virtualenv venv
. venv/bin/activate

pip install boto3

python stuff/monitor.py

$ sudo apt-get install python python-pip python-dev libffi-dev libssl-dev
$ sudo apt-get install python-virtualenv python-setuptools
$ sudo apt-get install libjpeg-dev zlib1g-dev swig

##### The log, error, files etc can be found at:
After
"python setup.py sdist develop"
We have:

Installed /usr/local/lib/python2.7/dist-packages/colorama-0.3.7-py2.7.egg
Searching for MarkupSafe>=0.23
Reading https://pypi.org/simple/MarkupSafe/
Downloading https://files.pythonhosted.org/packages/e0/bf/acc45baeb2d7333ed724c30af188640d9cb0be4b28533edfc3e2ae5aad72/MarkupSafe-2.0.0a1.tar.gz#sha256=beac28ed60c8e838301226a7a85841d0af2068eba2dcb1a58c2d32d6c05e440e
Best match: MarkupSafe 2.0.0a1
Processing MarkupSafe-2.0.0a1.tar.gz
Writing /tmp/easy_install-gouyg5/MarkupSafe-2.0.0a1/setup.cfg
Running MarkupSafe-2.0.0a1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gouyg5/MarkupSafe-2.0.0a1/egg-dist-tmp-Mh6yEA

The following error has occurred while trying to install Cuckoo!

Traceback (most recent call last):
  File "setup.py", line 129, in do_setup
    setuptools.setup(**kwargs)
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/develop.py", line 156, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 783, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 710, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 736, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 921, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1189, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1175, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-gouyg5/MarkupSafe-2.0.0a1/setup.py", line 56, in <module>
  File "/tmp/easy_install-gouyg5/MarkupSafe-2.0.0a1/setup.py", line 43, in run_setup
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 350, in _parse_attr
    value = getattr(module, attr_name)
AttributeError: 'module' object has no attribute '__version__'

**Comment by ELyndin** [comment]
issue has been resolved by installation old version MarkupSafe (1.1.1)
